
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_name character varying(100) COLLATE pg_catalog."default",
    contact_name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character(30) COLLATE pg_catalog."default" NOT NULL,
    billing_address text COLLATE pg_catalog."default" NOT NULL,
    city character varying(80) COLLATE pg_catalog."default",
    state character varying(80) COLLATE pg_catalog."default",
    country character(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    department_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    department_name character varying(50) COLLATE pg_catalog."default",
    location_type character varying(100) COLLATE pg_catalog."default",
    factory_id character(2) COLLATE pg_catalog."default",
    warehouse_id character(2) COLLATE pg_catalog."default",
    supervisor_employee_id integer,
    CONSTRAINT departments_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(30) COLLATE pg_catalog."default",
    department_id character varying(10) COLLATE pg_catalog."default",
    factory_id character(2) COLLATE pg_catalog."default",
    warehouse_id character(2) COLLATE pg_catalog."default",
    hire_date date NOT NULL,
    employment_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
    CONSTRAINT employees_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.factories
(
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    factory_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city character varying(80) COLLATE pg_catalog."default",
    state character varying(80) COLLATE pg_catalog."default",
    capacity_units_per_day integer NOT NULL DEFAULT 0,
    manager_employee_id integer,
    CONSTRAINT factories_pkey PRIMARY KEY (factory_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions
(
    transaction_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    material_id integer NOT NULL,
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(12, 2) NOT NULL,
    transaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    purchase_order_item_id integer,
    work_order_id integer,
    transaction_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT inventory_transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.machine_downtime
(
    downtime_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    machine_id integer NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    downtime_reason text COLLATE pg_catalog."default",
    impact_hours numeric(6, 2),
    CONSTRAINT machine_downtime_pkey PRIMARY KEY (downtime_id)
);

CREATE TABLE IF NOT EXISTS public.machines
(
    machine_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    production_line_id integer NOT NULL,
    machine_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    machine_type character varying(50) COLLATE pg_catalog."default",
    install_date date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    hourly_rate_usd numeric(10, 2),
    maintenance_cycle_days integer,
    CONSTRAINT machines_pkey PRIMARY KEY (machine_id)
);

CREATE TABLE IF NOT EXISTS public.maintenance_logs
(
    maintenance_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    machine_id integer NOT NULL,
    maintenance_date date NOT NULL,
    description text COLLATE pg_catalog."default",
    downtime_hours numeric(6, 2),
    cost numeric(12, 2),
    technician_employee_id integer NOT NULL,
    CONSTRAINT maintenance_logs_pkey PRIMARY KEY (maintenance_log_id)
);

CREATE TABLE IF NOT EXISTS public.maintenance_plans
(
    maintenance_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    machine_id integer NOT NULL,
    maintenance_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    frequency_days integer NOT NULL,
    estimated_duration_hours numeric(6, 2),
    assigned_employee_id integer NOT NULL,
    CONSTRAINT maintenance_plans_pkey PRIMARY KEY (maintenance_plan_id)
);

CREATE TABLE IF NOT EXISTS public.product_bom
(
    product_id integer NOT NULL,
    material_id integer NOT NULL,
    quantity_required integer,
    CONSTRAINT product_bom_pkey PRIMARY KEY (product_id, material_id)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT product_categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.production_lines
(
    production_line_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    line_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    line_type character varying(50) COLLATE pg_catalog."default",
    capacity_per_day integer NOT NULL DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    CONSTRAINT production_lines_pkey PRIMARY KEY (production_line_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category_id integer NOT NULL,
    dimensions character varying(100) COLLATE pg_catalog."default",
    weight_lb numeric(10, 2),
    load_capacity numeric(10, 2),
    unit_cost numeric(12, 2) DEFAULT 0,
    selling_price numeric(12, 2) DEFAULT 0,
    production_time_days integer,
    active_flag boolean NOT NULL DEFAULT true,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.products_inventory
(
    inventory_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    warehouse_id character(2) COLLATE pg_catalog."default" NOT NULL,
    product_id integer NOT NULL,
    quantity_on_hand integer NOT NULL DEFAULT 0,
    reorder_level integer NOT NULL DEFAULT 0,
    last_updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_pkey PRIMARY KEY (inventory_id)
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items
(
    purchase_order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    purchase_order_id integer NOT NULL,
    material_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_cost numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0,
    quantity_received integer NOT NULL DEFAULT 0,
    CONSTRAINT purchase_order_items_pkey PRIMARY KEY (purchase_order_item_id)
);

CREATE TABLE IF NOT EXISTS public.purchase_orders
(
    purchase_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    supplier_id integer NOT NULL,
    order_date date NOT NULL,
    expected_date date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    total_cost numeric(14, 2) NOT NULL DEFAULT 0,
    factory_id character(2) COLLATE pg_catalog."default",
    CONSTRAINT purchase_orders_pkey PRIMARY KEY (purchase_order_id)
);

CREATE TABLE IF NOT EXISTS public.quality_inspections
(
    inspection_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_id integer NOT NULL,
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    production_line_id integer NOT NULL,
    inspection_date date NOT NULL,
    inspector_employee_id integer NOT NULL,
    result character varying(20) COLLATE pg_catalog."default" NOT NULL,
    defect_count integer NOT NULL DEFAULT 0,
    CONSTRAINT quality_inspections_pkey PRIMARY KEY (inspection_id)
);

CREATE TABLE IF NOT EXISTS public.raw_material_suppliers
(
    material_supplier_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    material_id integer NOT NULL,
    supplier_id integer NOT NULL,
    factory_id character(2) COLLATE pg_catalog."default",
    unit_cost numeric(12, 2) NOT NULL,
    lead_time_days integer,
    preferred_supplier boolean DEFAULT false,
    CONSTRAINT raw_material_suppliers_pkey PRIMARY KEY (material_supplier_id),
    CONSTRAINT raw_material_suppliers_material_supplier_factory_key UNIQUE (material_id, supplier_id, factory_id)
);

CREATE TABLE IF NOT EXISTS public.raw_materials
(
    material_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    material_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    material_type character varying(50) COLLATE pg_catalog."default",
    unit_of_measure character varying(30) COLLATE pg_catalog."default" NOT NULL,
    dimensions character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT materials_pkey PRIMARY KEY (material_id)
);

CREATE TABLE IF NOT EXISTS public.raw_materials_inventory
(
    materials_inventory_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    material_id integer NOT NULL,
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    quantity_on_hand numeric(12, 2) NOT NULL DEFAULT 0,
    reorder_level numeric(12, 2) NOT NULL DEFAULT 0,
    last_updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT materials_inventory_pkey PRIMARY KEY (materials_inventory_id),
    CONSTRAINT materials_inventory_material_factory_key UNIQUE (material_id, factory_id)
);

CREATE TABLE IF NOT EXISTS public.returns
(
    return_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sales_order_id integer NOT NULL,
    customer_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    return_date date NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default" NOT NULL,
    condition character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'unknown'::character varying,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    resolution character varying(50) COLLATE pg_catalog."default",
    refund_amount numeric(12, 2) NOT NULL DEFAULT 0,
    restocked boolean NOT NULL DEFAULT false,
    warehouse_id character(2) COLLATE pg_catalog."default",
    handled_by_employee_id integer,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT returns_pkey PRIMARY KEY (return_id)
);

CREATE TABLE IF NOT EXISTS public.sales_order_items
(
    sales_order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sales_order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0,
    CONSTRAINT sales_order_items_pkey PRIMARY KEY (sales_order_item_id)
);

CREATE TABLE IF NOT EXISTS public.sales_orders
(
    sales_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer NOT NULL,
    order_date date NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    total_amount numeric(14, 2) NOT NULL DEFAULT 0,
    warehouse_id character(2) COLLATE pg_catalog."default" NOT NULL,
    shipping_address text COLLATE pg_catalog."default",
    CONSTRAINT sales_orders_pkey PRIMARY KEY (sales_order_id)
);

CREATE TABLE IF NOT EXISTS public.shipments
(
    shipment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sales_order_id integer NOT NULL,
    warehouse_id character(2) COLLATE pg_catalog."default" NOT NULL,
    ship_date date,
    delivery_date date,
    carrier character varying(100) COLLATE pg_catalog."default",
    tracking_number character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    CONSTRAINT shipments_pkey PRIMARY KEY (shipment_id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    supplier_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    supplier_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contact_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    street text COLLATE pg_catalog."default",
    city character varying(80) COLLATE pg_catalog."default",
    state character varying(80) COLLATE pg_catalog."default",
    lead_time_days integer,
    rating numeric(3, 1),
    zipcode character(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public.warehouses
(
    warehouse_id character(2) COLLATE pg_catalog."default" NOT NULL,
    warehouse_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city character varying(80) COLLATE pg_catalog."default",
    state character varying(80) COLLATE pg_catalog."default",
    storage_capacity_units integer NOT NULL DEFAULT 0,
    manager_employee_id integer,
    CONSTRAINT warehouses_pkey PRIMARY KEY (warehouse_id)
);

CREATE TABLE IF NOT EXISTS public.work_orders
(
    work_order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    factory_id character(2) COLLATE pg_catalog."default" NOT NULL,
    production_line_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    start_date date,
    due_date date,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'normal'::character varying,
    CONSTRAINT work_orders_pkey PRIMARY KEY (work_order_id)
);

ALTER TABLE IF EXISTS public.departments
    ADD CONSTRAINT fk_departments_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.departments
    ADD CONSTRAINT fk_departments_supervisor FOREIGN KEY (supervisor_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.departments
    ADD CONSTRAINT fk_departments_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fk_employees_department FOREIGN KEY (department_id)
    REFERENCES public.departments (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fk_employees_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fk_employees_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factories
    ADD CONSTRAINT fk_factories_manager FOREIGN KEY (manager_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_inv_txn_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_inv_txn_item_order FOREIGN KEY (purchase_order_item_id)
    REFERENCES public.purchase_order_items (purchase_order_item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uq_inv_txn_purchase_item
    ON public.inventory_transactions(purchase_order_item_id);


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_inv_txn_material FOREIGN KEY (material_id)
    REFERENCES public.raw_materials (material_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_inv_txn_work_order FOREIGN KEY (work_order_id)
    REFERENCES public.work_orders (work_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uq_inv_txn_work_order
    ON public.inventory_transactions(work_order_id);


ALTER TABLE IF EXISTS public.machine_downtime
    ADD CONSTRAINT fk_machine_downtime_machine FOREIGN KEY (machine_id)
    REFERENCES public.machines (machine_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.machines
    ADD CONSTRAINT fk_machines_production_line FOREIGN KEY (production_line_id)
    REFERENCES public.production_lines (production_line_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.maintenance_logs
    ADD CONSTRAINT fk_maintenance_logs_machine FOREIGN KEY (machine_id)
    REFERENCES public.machines (machine_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.maintenance_logs
    ADD CONSTRAINT fk_maintenance_logs_technician FOREIGN KEY (technician_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.maintenance_plans
    ADD CONSTRAINT fk_maintenance_plans_employee FOREIGN KEY (assigned_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.maintenance_plans
    ADD CONSTRAINT fk_maintenance_plans_machine FOREIGN KEY (machine_id)
    REFERENCES public.machines (machine_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.production_lines
    ADD CONSTRAINT fk_production_lines_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id)
    REFERENCES public.product_categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products_inventory
    ADD CONSTRAINT fk_inventory_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products_inventory
    ADD CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_order_items
    ADD CONSTRAINT fk_purchase_order_items_material FOREIGN KEY (material_id)
    REFERENCES public.raw_materials (material_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_order_items
    ADD CONSTRAINT fk_purchase_order_items_order FOREIGN KEY (purchase_order_id)
    REFERENCES public.purchase_orders (purchase_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT fk_factory_id FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quality_inspections
    ADD CONSTRAINT fk_quality_inspections_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quality_inspections
    ADD CONSTRAINT fk_quality_inspections_inspector FOREIGN KEY (inspector_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quality_inspections
    ADD CONSTRAINT fk_quality_inspections_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quality_inspections
    ADD CONSTRAINT fk_quality_inspections_production_line FOREIGN KEY (production_line_id)
    REFERENCES public.production_lines (production_line_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.raw_material_suppliers
    ADD CONSTRAINT raw_material_suppliers_factory_id_fkey FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.raw_material_suppliers
    ADD CONSTRAINT raw_material_suppliers_material_id_fkey FOREIGN KEY (material_id)
    REFERENCES public.raw_materials (material_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.raw_material_suppliers
    ADD CONSTRAINT raw_material_suppliers_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.raw_materials_inventory
    ADD CONSTRAINT fk_mat_inv_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.raw_materials_inventory
    ADD CONSTRAINT fk_mat_inv_material FOREIGN KEY (material_id)
    REFERENCES public.raw_materials (material_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.returns
    ADD CONSTRAINT fk_returns_customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.returns
    ADD CONSTRAINT fk_returns_employee FOREIGN KEY (handled_by_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.returns
    ADD CONSTRAINT fk_returns_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.returns
    ADD CONSTRAINT fk_returns_sales_order FOREIGN KEY (sales_order_id)
    REFERENCES public.sales_orders (sales_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.returns
    ADD CONSTRAINT fk_returns_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_order_items
    ADD CONSTRAINT fk_sales_order_items_order FOREIGN KEY (sales_order_id)
    REFERENCES public.sales_orders (sales_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_order_items
    ADD CONSTRAINT fk_sales_order_items_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_orders
    ADD CONSTRAINT fk_sales_orders_customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales_orders
    ADD CONSTRAINT fk_sales_orders_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shipments
    ADD CONSTRAINT fk_shipments_sales_order FOREIGN KEY (sales_order_id)
    REFERENCES public.sales_orders (sales_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.shipments
    ADD CONSTRAINT fk_shipments_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouses (warehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.warehouses
    ADD CONSTRAINT fk_warehouses_manager FOREIGN KEY (manager_employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work_orders
    ADD CONSTRAINT fk_work_orders_factory FOREIGN KEY (factory_id)
    REFERENCES public.factories (factory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work_orders
    ADD CONSTRAINT fk_work_orders_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work_orders
    ADD CONSTRAINT fk_work_orders_production_line FOREIGN KEY (production_line_id)
    REFERENCES public.production_lines (production_line_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;